### ISSUE TITLE
[Tutorial 1] Formating issue

### ISSUE THREAD

**Issue by doisyg** [splintered-reality/py_trees_ros#49] opened 2019-01-04 13:23 UTC
Hello,
I am completely new at py_tree_ros and I just started following the tutorials. I am under Melodic and when executing the first tutorial, the output of **rostopic echo /tree/blackboard** seems badly formatted:

```
data: "\e[32mBlackboard\n\e[0m\e[36m  battery             \e[0m:\n\e[33m    header: \n\e\
  [0m\e[33m      seq: 12173\n\e[0m\e[33m      stamp: \n\e[0m\e[33m        secs: 1546607831\n\
  \e[0m\e[33m        nsecs: 515712022\n\e[0m\e[33m      frame_id: ''\n\e[0m\e[33m\
  \    voltage: nan\n\e[0m\e[33m    current: nan\n\e[0m\e[33m    charge: nan\n\e[0m\e\
  [33m    capacity: nan\n\e[0m\e[33m    design_capacity: nan\n\e[0m\e[33m    percentage:\
  \ 0.0\n\e[0m\e[33m    power_supply_status: 2\n\e[0m\e[33m    power_supply_health:\
  \ 1\n\e[0m\e[33m    power_supply_technology: 2\n\e[0m\e[33m    present: True\n\e\
  [0m\e[33m    cell_voltage: []\n\e[0m\e[33m    location: ''\n\e[0m\e[33m    serial_number:\
  \ ''\n\e[0m\e[36m  battery_low_warning \e[0m: \e[33mTrue\n\e[0m\e[0m"

```
Additionally I had to pip install pygraphviz and in order to start the first tutorial.

**Comment by stonier** [comment] 2019-01-04 13:27
Aye, that it does. ROS2 can't handle escape sequences and newlines, but ROS1 should be fine. I'll try and reproduce on my melodic install at home on the weekend.

Thanks for the heads up on pygraphviz. I'll see to that.

**Comment by doisyg** [comment] 2019-01-04 13:57
And if that can help, formating is okay when using the **py-trees-blackboard-watcher** tool.

**Comment by stonier** [comment] 2019-01-06 04:00
**pygraphviz**

It was already [bugfixed](https://github.com/stonier/rqt_py_trees/commit/6153ec046a446e8369490151711bfa3de2080656) in rqt_py_trees, just not released as a deb on Melodic.

The bugfixed version, 0.3.1, is [on it's way](https://github.com/ros/rosdistro/pull/19871).

**Comment by stonier** [comment] 2019-01-06 04:07
**Formatting**

Reproduced on melodic. That affects all of the introspective publishers (e.g. `tree/ascii/tree`).

I'll have to dig deeper to see if it was a change in py_trees from xenial to melodic or (more likely) rostopic changed under the hood in the interim. The ROS2 version of this switched to using yaml features to improve code reuse, but lost string formatting along the way as well, so I'm creating a variety of tools there (like `py-trees-blackboard-watcher`) to compensate.

**Comment by stonier** [comment] 2019-01-06 04:48
Looks like the change came in with v0.6.6 of genpy (see the relevant PR [here](https://github.com/ros/genpy/pull/79) which matches what is going on in ROS2 (see https://github.com/ros2/ros2cli/issues/154).

Their reasons for doing so are good (be able to pipe output of rostopic echo into a publisher), so that is unlikely to get reverted and further updating ROS1's rostopic pub to re-enable formatting is likely to be tricky / not on the radar of the ROS devs. 

In that light, the best thing to do here would be to extend `py-trees-blackboard-watcher` so it can format the whole blackboard (I've done so [here](https://github.com/stonier/py_trees_ros/commit/2238601c1028ae98a9378c52eff5c9dd6bc90bef#diff-050d8d797e6dd6dda61a3291370bb938R84) for the ROS2 version) and create a `py-trees-tree-watcher` script as well (also started similar [here](https://github.com/stonier/py_trees_ros/tree/devel/py_trees_ros/programs) for ROS2).

I don't have too many cycles at the moment to work on the melodic side, if you'd like to send in PR's though, I'd happily help get them released.

**Comment by doisyg** [comment] 2019-01-07 08:55
Thanks for the clarification. we don't use yet py trees for our robot applications, but we are currently considering the idea and may test it. If we adopt it, we may fix the formatting with a PR, but that's no going to happen soon.

**Comment by stonier** [comment] 2019-02-02 17:27
`py-trees-blackboard-watcher` and `py-trees-tree-watcher` now make up for this regression. 

Commits in 53bb3413daa04f6e18754593e1c3ac14bcb21e4f and 8c036fb73b0f3646f6d94aa13676cd8a9c495903

Releasing in `v0.5.15`.

**Closed as completed by stonier** 2019-02-02 17:27 UTC
